services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - ./session/:/app/session
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8888"
    expose:
      - 8888
volumes:
  pupp_app:
