stages:
  - staging
  - production

deploy_staging:
  stage: staging
  environment:
    name: Staging
  script:
    - echo "Value DEBUG from Staging $DEBUG"

deploy_production:
  stage: publish
  environment:
    name: Production
  when: manual
  script:
    - echo "Value DEBUG from Production $DEBUG"
